version: '3.8'

networks:
  airflow-net:
    driver: bridge

volumes:
  postgres-data:
  airflow-logs:

services:
  postgres:
    image: postgres:14
    networks:
      - airflow-net
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow123
      POSTGRES_DB: airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  airflow-webserver:
    image: apache/airflow:2.9.3
    networks:
      - airflow-net
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow123@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow-logs:/opt/airflow/logs
    command: webserver
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.9.3
    networks:
      - airflow-net
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow123@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow-logs:/opt/airflow/logs
    command: scheduler
    restart: always
